services:
  immich<__instance>:
    image: ghcr.io/immich-app/immich-server:${IMMICH<__INSTANCE>__TAG?}
  immich<__instance>-ml:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH<__INSTANCE>___ML__TAG?}
  immich<__instance>-postgres:
    image: ghcr.io/immich-app/postgres:${IMMICH<__INSTANCE>___POSTGRES__TAG?}
  immich<__instance>-redis:
    image: docker.io/valkey/valkey:${IMMICH<__INSTANCE>___REDIS__TAG?}
